### ISSUE TITLE
Fondo en color claro

### ISSUE THREAD

**Issue by ehooo** [CodelyTV/jetbrains-theme#15]
Al instalar el plugin se pone el tema claro por defecto, pero cuando lo cambio al oscuro sigue apareciendo claro el color de fondo principal.
Creo que le quedaría mejor un color oscuro como hace el "Darcula"

![image](https://user-images.githubusercontent.com/709565/99198666-618cdb00-279a-11eb-8eaf-4ae31daf217c.png)

No es si ha sido un bug añadido al poner el color claro.

**Comment by Missionpage** [comment]
No es un _bug_, simplemente debes cambiar el "**Theme**" en "**Appearance & Behavior**".


![](https://i.gyazo.com/07e9944509ad4416ba08605851799714.png)

Espero que te haya ayudado! 😉

**Comment by ehooo** [comment]
@Missionpage muchas gracias era eso.

**Comment by JavierCane** [comment]
Mil gracias por el report @ehooo y por echar una mano @Missionpage 😊🙌!!!
