### ISSUE TITLE
Codely Dark Theme and Scala

### ISSUE THREAD

**Issue by joucogi** [CodelyTV/jetbrains-theme#23]
Do you see the right colours with Codely Dark theme and Scala language? because I am not. 
I don't know whether it is my Intellij fault or theme is not configured.

![image](https://user-images.githubusercontent.com/8606896/116778778-4d9d1300-aa74-11eb-90d1-9a39369539c8.png)

With Codely and Codely Blue theme the colours are shown correctly but not with Codely Dark.
If wou need a PR just let me know.

**Comment by rgomezcasas** [comment]
Create the PR, please 😊🙏
