### ISSUE TITLE
Show whitespaces - Dark themes

### ISSUE THREAD

**Issue by gon250** [CodelyTV/jetbrains-theme#26]
## Description 
There is an issue while using the theme in Webstorm to show whitespaces, only when using dark options (Codely, Codely Blue, Codely Dark).

<img width="228" alt="Screenshot 2021-06-01 at 11 25 47" src="https://user-images.githubusercontent.com/1652286/120300335-1f596000-c2cc-11eb-8246-a5ac393aaf45.png">

Codely Light theme is working fine

<img width="332" alt="Screenshot 2021-06-01 at 11 27 04" src="https://user-images.githubusercontent.com/1652286/120300519-4d3ea480-c2cc-11eb-948b-15c85d981f40.png">

### Reproduction 
* Open a project in Webstorm with codelytv theme installed.
* Enable show whiitespaces 
<img width="701" alt="Screenshot 2021-06-01 at 11 32 04" src="https://user-images.githubusercontent.com/1652286/120301299-ff766c00-c2cc-11eb-9ae6-da6619317999.png">
* Set a codelytv dark theme option.

#### Actual result 
You cant see dots to identify white spaces.

#### Expected result
See whitespace dots as in other themes.

**Comment by Mzea1995** [comment]
Hi @gon250 I had the same problem, I could fix it changing the white spaces color on `Editor > Color Scheme > General` : `Text > Whitespaces`.
I hope that help you.

**Comment by gon250** [comment]
@Mzea1995 I made the same change and it works fine after that, just wanted to create the issue to let them know about it. Btw I use Hex: EBDBB2

**Comment by rgomezcasas** [comment]
Reopening since this has been fixed in the Codely theme, but not in the dark and blue variant
