### ISSUE TITLE
Can't view active search customizations in dark theme

### ISSUE THREAD

**Issue by fabriziofs** [CodelyTV/jetbrains-theme#43]
Trying to perform a file search I have this situation: 
<img width="698" alt="image" src="https://user-images.githubusercontent.com/62360034/225887867-f6e64d57-df38-4b64-b5bc-889fa868474f.png">

I've the "Words" option active, but in the dark theme I can't see it. Trying the same thing with the Codely Theme light version:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/62360034/225888634-7f1924dc-c4c1-46fe-bc6a-68da209c4f62.png">

I think this erros is similar to #35

Thanks! <💚>

**Comment by SantiGodoy** [comment]
Same issue with theme version 2.2.5 and IntelliJ version 2023.3.2
