### ISSUE TITLE
Choose Codely,Right side is white

### ISSUE THREAD

**Issue by BaiMingxu** [CodelyTV/jetbrains-theme#48]
Android Studio Jellyfish 2023.3.1 Canary 11
Dark on the left and white on the right

**Comment by JavierCane** [comment]
Hi @BaiMingxu, we will check it out. Just to confirm:

- It still does not work after reinstalling the theme?
- Other user reported that the Codely Blue still works properly, is it also your case?

Thanks!

**Comment by BaiMingxu** [comment]
Reloading is fine, thank you
