### ISSUE TITLE
there is white background bottom scrollbar in editor

### ISSUE THREAD

**Issue by dudong0726** [CodelyTV/jetbrains-theme#5]
os: mac pro catalina

idea: IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019

codelyTV: 1.0.4

![image](https://user-images.githubusercontent.com/1704803/69131770-c234f980-0aed-11ea-9e10-7a3f643e9727.png)

**Comment by dudong0726** [comment]
also found in Terminal tab.

**Comment by JavierCane** [comment]
Thanks for the report!

I can't reproduce the issue right now. I'll try in a few days with the same MacOS version 😊

In the meantime, if anybody wants to try to fix it, you would be more than welcomed 🤟🙌

**Comment by rgomezcasas** [comment]
@dudong0726 Maybe you have the option “Use contrast scrollbars” (Preferences/Settings | Appearance & Behavior | Appearance) enabled?

**Comment by JavierCane** [comment]
Version 1.1.1 released fixing this issue: https://github.com/CodelyTV/jetbrains-theme/releases/tag/1.1.1

The release has been submitted to JetBrains and "it will be processed within two business days" 😊🤟

Thanks for the report!
