### ISSUE TITLE
Problema al reiniciar, se pierde el tema

### ISSUE THREAD

**Issue by Coinuma** [CodelyTV/jetbrains-theme#8]
No se si el problema es de este tema concretamente pero lo llevo usando ya meses y cada vez que abro el IDE (En este caso PhpStorm) me toca abrir las preferencias del IDE, cambiar el tema a cualquier otro y volver a ponerlo en el de CodelyTY para que funcione.

La apariencia del codigo es la de CodelyTV pero el resto (barras de estado, explorador de ficheros, etc.) estan con uno de los otros temas de Material Theme.

Lo he probado en al menos 3 entornos diferentes con el mismo resultado.

**Comment by JavierCane** [comment]
¡Hostias!

Primero, gracias por el reporte y perdón por las molestias.

Dicho esto, a nosotros sólo nos ha pasado cuando cambiamos el nombre del Code Style de `CodelyTV - Gruvbox ` a `CTV - Gruvbox Dark`, con lo que no sabríamos reproducirlo :S

A pesar de que no actualices el plugin, ¿con que cierres el IDE y lo abras ya se pierde?

**Comment by JavierCane** [comment]
Dupe: https://github.com/CodelyTV/jetbrains-theme/issues/9

**Comment by bnd170** [comment]
Soy la misma persona, he reabierto el issue en ingles por si a alguien que no hable español le pasa lo mismo y le puede resultar de utilidad. Ademas usé una cuenta que no era :joy: ignoro si se puede eliminar esto.

Gracias de antemano!
