### ISSUE TITLE
Theme loses its appearance when IDE's restart

### ISSUE THREAD

**Issue by bnd170** [CodelyTV/jetbrains-theme#9]
I'm using it for months and every time I open the IDE (In this case PhpStorm) I have to open the IDE settings, change the theme to any other and put it back in the one of CodelyTY to make it works.

The appearance of the code is that of CodelyTV but the rest (status bars, relationship explorer, etc.) are with one of the other themes of Material Theme.

I have tried it in at least 3 different environments with the same result.

**Comment by JavierCane** [comment]
Firstly, thanks for the report and sorry for the inconveniences.

Said that, we only had this kind of problem when we updated the Code Style name from `CodelyTV - Gruvbox ` to `CTV - Gruvbox Dark`, so we don't know how to reproduce the issue.

One question: Does the issue happen even if you don't update the CodelyTV them plugin? I mean, you have to re-select the Code Style just closing and opening the IDE without applying any updates?

Thanks!

**Comment by bnd170** [comment]
This issue happens to me sience i've started to use the theme, not just sience last update :(

It's a very stange issue because it only makes troubles when Material Theme runiung, if I disable Matherial Theme, your theme works properly.
